config/routes.rb
Rails.application.routes.draw do
  resources :neighborhoods
  resources :categories
  resources :cities
  resources :states
  resources :properties
  resources :photos
  resources :home, only: [:show, :index]
  resources :messages 
  match "admin", to: "properties#index", via: :get
  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :neighborhood
 
  belongs_to :category, counter_cache: true
  belongs_to :city
  belongs_to :state
  has_many :photos  


  CURRENCY = ["Lps", "$"]

  scope :category, -> (category_id) { where category_id: category_id }
  scope :city, -> (city_id) { where city_id: city_id }


def self.search(term, page)
  if term
    where('description LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('id DESC')
  else
    paginate(page: page, per_page: 5).order(created_at: :desc)
  end
end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "nimer", password: "nimer",  except: :show

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.search(params[:term], params[:page])
    @term = params[:term]
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @photo = Photo.new
    @photos  = @property.photos.order(:sort)
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
    @photo = Photo.new
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    n=Neighborhood.find_or_create_by(name: params[:neighborhood]) do |n|
      n.name = params[:neighborhood]
    end
    @property.neighborhood= n
     
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update

    n=Neighborhood.find_or_create_by(name: params[:neighborhood]) do |n|
      n.name = params[:neighborhood]
    end
    @property.neighborhood= n

    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :description, :state_id, :city_id, :neighborhood, :rooms, :category_id, :price, :currency)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true, :class=>"ui form") do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= collection_select(:property, :category_id, Category.all, :id, :name,{}, {class: "ui fluid dropdown"}) %>

  </div>
  <div class="field">
    <%= form.label "Título" %>
    <%= form.text_field :name, id: :property_name, size: 50%>
  </div>


  <div class="field">
    <%= form.label "Descripción" %>
    <%= form.text_area :description, cols: 50, rows: 10, id: :property_description %>
  </div>


<div class="field">
        <%= form.label "Status" %>
     <%= collection_select(:property, :state_id, State.all, :id, :name, :include_blank => true)  %>

  </div>

<div class="field">
      <%= form.label "Ciudad" %>
     <%= collection_select(:property, :city_id, City.all, :id, :name) %>

  </div>

  <div class="field">
    <%= form.label "Colonia/Barrio" %> 
 
    <input class="form-control mr-sm-2" type="text" placeholder="Colonia", data-behavior="autocomplete"  id="neighborhood" name="neighborhood" value="<%= property.neighborhood %>">

  </div>


  <div class="two fields">

    <div class="field">
    <%= form.label "Precio"%>
    <%= form.select :currency, ['LPS', '$'] %>
    </div>

    <div class="field">
    <%= form.text_field :price, id: :property_price %>
    </div>
  </div>

  

  <div class="field">
    <%= form.label "Habitaciones" %>
    <%= form.text_field :rooms, id: :property_rooms %>
  </div>


  <div class="actions">
     <input type="submit" class="ui button teal" value="Guardar Cambios">
  </div>
<% end %>

app/views/properties/_photos.html.erb
<h1>Fotos</h1>
  <div id="photosWrapperAdmin">
    
    <% property.photos.each do |photo| %>
    
    <div id="photoAdmin">
     <%= image_tag photo.image.url(:thumb) %>
     

  <%= form_with(model: photo,:class=>"ui form" ) do |f| %>
    <%= f.text_field :description %>
    <%= f.submit "Guardar Cambio", :class=>"ui button" %>
  <% end %>

    <%= link_to 'Borrar Foto', photo, method: :delete, data: { confirm: 'Are you sure?' } %> 
 
    </div>
 
    
    <% end %>

  </div>

app/views/properties/edit.html.erb
<div class="ui container">
<h1>Editar propiedad</h1>
<%= render 'form', property: @property %>



<%= render 'photos', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

</div>

app/views/properties/index.html.erb
<style type="text/css">
   .tabledesc{
    font-size: 10px;
  }
</style>

<p id="notice"><%= notice %></p>

<div class="ui container">

<h1>Listado <a href="/properties/new" class="ui teal labeled icon button">  <i class="add icon labeled"></i>Nueva Propiedad</a>
 </h1>

<div class="ui  centered grid">
  <div class="six wide column">
<%= form_tag("./", method: :get, :class=>"ui form")  do %>
    <%= text_field_tag(:term,'', size: 10)%>
     <div class="fluid mini ui submit button teal "><i class="search icon"></i>Buscar</div>
    <% end %>
</div>
</div>

<% if @term %>
 Resultados de la busqueda <strong><%=@term%></strong>
<%end%>

<table class="ui celled striped table">

  <thead>
    <tr>
      <th>Título</th>
      <th>Descripción</th>
      <th>Ciudad</th>
      <th>Colonia</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td width="180"><%= property.name %>
          <% if property.state%>
        <% if property.state.name != "Normal" %>
        <div class="ui  horizontal label orange"><%= property.state  %></div>
        <%end%>
      <%end%> </td>
        <td class="tabledesc"><%= property.description %></td>
        <td><%= property.city %></td>
        <td><%= property.neighborhood %></td>
        <td><%= property.category %></td>
        <td><%= link_to 'Fotos', property, :class => "ui primary basic button" %>  </td>
        <td><%= link_to 'Editar', edit_property_path(property), :class => "ui primary basic button" %></td>
        <td><%= link_to 'Borrar', property, :class => "ui primary basic button", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<%= will_paginate @properties %>

 

app/views/properties/new.html.erb
<div class="ui  centered grid">
  <div class="six wide column">

<h1>Agregar Propiedad</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

</div>
</div>

app/views/properties/show.html.erb
<script type="text/javascript">
$(function() {
  $('.sortable').railsSortable();
});
</script>

<div id="showAdmin">
<p id="notice"><%= notice %></p>

<h1>
   
  <%= @property.name %> ( <%= link_to 'Editar', edit_property_path(@property) %> | <a href="/home/<%=@property.id%>">Ver</a> ) 

</h1>

<p>
  <strong>Descripción:</strong>
  <div>
  <%= @property.description %>
</div>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @property.city.name %>
</p>

<p>
  <strong>Barrio/Colonia:</strong>
  <%= @property.neighborhood.name %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @property.category.name %>
</p>

<p>
  <strong>Cuartos:</strong>
  <%= @property.rooms %>
</p>

<div class="ui message">

<%= form_for @photo, url: photos_path, html: { multipart: true, :class=>"ui form" } do |form| %>
  <br/>
  <%= form.file_field  :image, :class=>"ui button", multiple: true, accept: 'image/png,image/jpeg' %>

  <%= form.hidden_field :property_id, :value => @property.id%>
  <p>
  <%= form.submit "Subir Fotos", :class=>"ui button",  size: 20, :id => "addphotosubmit" %>
</p>
<% end %>
</div>



<h1>Fotos</h1>
  <div id="photosWrapperAdmin">
    
<table class="ui table collapsing"  >


  <tbody class="sortable"> 
    <% @photos.each do |photo| %>
      <tr id = "<%=photo.sortable_id%>" class="six wide"> 
        <td>
          <%= image_tag photo.image.url(:thumb) %>
         

      <%= form_with(model: photo,:class=>"ui form" ) do |f| %>
        <%= f.text_field :description, :size=>10 %>
        <%= f.submit "Guardar Cambio", :class=>"ui button tiny" %>
                <span><%= link_to 'Borrar', photo, method: :delete, data: { confirm: 'Are you sure?' } %> </span>

      <% end %>
        
     
        
      </td>
      </tr>
        
 
    
    <% end %>
 </tbody>
    </table>
  </div>

</div>