config/routes.rb
Rails.application.routes.draw do
  resources :neighborhoods
  resources :categories
  resources :cities
  resources :states
  resources :properties
  resources :photos
  resources :home, only: [:show, :index]
  resources :messages 
  match "admin", to: "properties#index", via: :get
  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :properties

	def to_s
		self.name
	end
end

app/models/city.rb
class City < ApplicationRecord

	def to_s
		self.name
	end

	has_many :properties
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :phone_number, :body
  validates :name, :email, :phone_number, :body, presence: true
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
	def self.search(term)
		where('LOWER(name) LIKE :term', term: "%#{term.downcase}%")
	end

	def to_s
		self.name
	end
	
	has_many :properties
end

app/models/photo.rb
class Photo < ApplicationRecord
	include RailsSortable::Model
	set_sortable :sort 
	belongs_to :property
	has_attached_file :image, styles: { medium: "800x800>", thumb: "250x250>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :neighborhood
 
  belongs_to :category, counter_cache: true
  belongs_to :city
  belongs_to :state
  has_many :photos  


  CURRENCY = ["Lps", "$"]

  scope :category, -> (category_id) { where category_id: category_id }
  scope :city, -> (city_id) { where city_id: city_id }


def self.search(term, page)
  if term
    where('description LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('id DESC')
  else
    paginate(page: page, per_page: 5).order(created_at: :desc)
  end
end

end

app/models/state.rb
class State < ApplicationRecord
	has_many :properties

	def to_s
		self.name
	end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
    @city = City.new
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_url, notice: 'Ciudad agregada' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'Ciudad actualizada' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'Ciudad Borrada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

		@category_id = params[:category_id]
		@city_id = params[:city_id]

		@properties = Property.where(nil)

		@properties = @properties.category(params[:category_id]) if @category_id.present?
		@properties = @properties.city(params[:city_id]) if params[:city_id].present?
		@term = params[:term]
		@properties = @properties.where("description LIKE ?", "%#{@term}%")

		@category = Category.find(params[:category_id]) if params[:category_id].present?
		@categories = Category.all()
		
	end

	def show
		@message = Message.new
		@property = Property.find(params[:id])
		@photo = Photo.new
		@categories = Category.all()
		@propertiesCount = Property.count
		@photos  = @property.photos.order(:sort)

	end

end


	

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
   before_action :set_photo, only: [:show, :edit, :update, :destroy]

	def new
   		@photo = Photo.new
 	end

 	def destroy
 		@property = Property.find(@photo.property_id)

	    @photo.destroy

	    respond_to do |format|
	      format.html { redirect_to @property, notice: 'Photo was successfully destroyed.' }
	      format.json { head :no_content }
	    end
  	end

 	def create

 		params[:photo][:image].each { |img|
 			 @photo = Photo.new()
 			 @photo.image = img
 			 @photo.property_id = params[:photo][:property_id]
 			 @photo.save
 		}
 		
 		@property = Property.find(params[:photo][:property_id])

		respond_to do |format|
			format.html { redirect_to @property, notice: 'Foto fue agregada con exito' }
			format.json { render :show, status: :created, location: @property }
		 end
    end
	 
	def update
	  @photo.update!(photo_params)
	  render json: @photo
	end

	private

    def set_photo
      @photo = Photo.find(params[:id])
    end

	def photo_params
	  params.require(:photo).permit(:image, :description, :property_id)
 	end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
	  before_action :set_state, only: [:show, :edit, :update, :destroy]

	def index
		@states = State.all
    @state = State.new
	end

	  # GET /cities/new
  def new
    @state = State.new
  end

	def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to states_url, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

 private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:name)
    end


    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inverprop Bienes Raices</title>
    <%= csrf_meta_tags %>
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="ui stackable menu">
   <%= link_to '+ Agregar Propiedad', new_property_path, :class=>"item" %>   	<a href="/properties/" class="item">Listado</a> <a href="/categories/" class="item">Categorias</a>   <%= link_to 'Ciudades', cities_path, :class=>"item" %> <%= link_to 'Status', states_path, :class=>"item" %>
 </div>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/home.html.erb
<%= semantic_flash %>
<!DOCTYPE html>
<html>

  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-1368775-11"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1368775-11');
</script>

    <title>Inverprop Bienes Raices 2.0</title>
    <%= csrf_meta_tags %>
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
  	 

    <div class="ui grid stackable">

      <div class="four wide column center aligned">
        <a href="/"><img src="/icons/logo.png" width="160"></a>
      </div>

      <div class="ten wide column  center aligned">
        

         <div class="ui horizontal list " style="margin-top:20px;">

          <a class="item " >
            <i class="icon mail"></i> inverprop@ngabrie.com
          </a>

          <a class="item">
            <i class="icon whatsapp"></i> +(504) 9402-9402
          </a>

          <a class="item">
            <i class="phone icon"></i> +(504) 2221-0870
          </a>

        </div>
       </div>

    </div>

 

     <%= yield %>
 
 <div class="ui segment center aligned blue inverted">
           Inverprop Bienes Raices, Todos Los Derechos Reservados
 
</div>

	 
 


  </body>
</html>